- Makefile
`make release-component-version > COMPONENT_VERSION`
Stash COMPONENT_VERSION file.
`env COMPONENT_VERSION=$(cat COMPONENT_VERSION) make release`
(in pseudo-bash)
> Add release-component-version make target

- catalog/locales/en/messages.gotext.json
- service/cluster/xtra_db_cluster.go
- service/k8sclient/k8client.go
- service/k8sclient/k8client_test.go
- service/k8sclient/kubectl/kubectl.go
- service/k8sclient/kubectl/kubectl_test.go
https://jira.percona.com/browse/PMM-6348
FB: https://github.com/Percona-Lab/pmm-submodules/pull/1002
> PMM-6348 Handle kubectl versions

- go.mod
- go.sum
- service/cluster/xtra_db_cluster.go
- service/k8sclient/kubectl/kubectl.go
- service/k8sclient/kubectl/kubectl_test.go
https://jira.percona.com/browse/PMM-6457
ref:
- https://github.com/Percona-Lab/pmm-api-tests/pull/125
- https://github.com/percona-platform/dbaas-controller/pull/58
- https://github.com/percona/pmm-managed/pull/468
- https://github.com/percona/pmm/pull/582
- https://github.com/Percona-Lab/pmm-submodules/pull/1124
> PMM-6457 Add kubectl of pmm-server.

- .github/workflows/ci.yml
- .github/workflows/cleanup.yml
- cmd/dbaas-controller/main.go
- go.mod
- go.sum
- utils/logger/zap_logger.go
ticket https://jira.percona.com/browse/SAAS-391
> SAAS-391 Use major versions for actions

- go.mod
- go.sum
- service/cluster/psmdb_cluster.go
- service/cluster/xtra_db_cluster.go
- service/k8sclient/k8client.go
- tests/go.mod
- tests/go.sum
- tests/psmdbcluster/psmdb_cluster_test.go
- tests/xtradbcluster/xtra_db_cluster_test.go
https://jira.percona.com/browse/PMM-7180
FB: https://github.com/Percona-Lab/pmm-submodules/pull/1325
https://github.com/percona/pmm-managed/pull/587
https://github.com/percona-platform/dbaas-api/pull/80
> PMM-7180 Add paused state.

- Makefile
Currently, it just hangs with `aws configure` waiting for the input
in the background.
> Fix running `make help`

- service/k8sclient/internal/psmdb/psmdb_types.go
- service/k8sclient/k8sclient.go
PSMDB operator does not handle well special characters in the password. We remove them for now until K8SPSMDB-364 is fixed.
https://github.com/Percona-Lab/pmm-submodules/pull/1616
> PMM-7701 Remove special chars from passwords

- service/cluster/xtra_db_cluster.go
- service/k8sclient/internal/pxc/pxc_types.go
- service/k8sclient/internal/pxc/pxc_types_test.go
- service/k8sclient/k8sclient.go
- service/k8sclient/k8sclient_test.go
> Changes from 2.23.0

- service/cluster/psmdb_cluster.go
- service/k8sclient/common/types.go
- service/k8sclient/internal/psmdb/psmdb_types.go
- service/k8sclient/internal/psmdb/psmdb_types_test.go
- service/k8sclient/internal/pxc/pxc_types.go
- service/k8sclient/k8sclient.go
- service/k8sclient/k8sclient_test.go
I generalized the way we get state of clusters by modifying the getPXCState we already had.
> PMM-8094 PSMDB: fix clusters stuck in paused

- service/k8sclient/k8sclient.go
[PMM-9496](https://jira.percona.com/browse/PMM-9496)
> Make shorter secretName "victoria-metrics-operator" to desrease servicename

- service/k8sclient/secrets.go
PMM-9745
https://github.com/Percona-Lab/pmm-submodules/pull/2398
> PMM-9745 create password for replication

- .github/workflows/ci.yml
- Makefile
- service/k8sclient/internal/kubectl/kubectl.go
- service/k8sclient/internal/kubectl/kubectl_test.go
PMM-7
Build: https://github.com/Percona-Lab/pmm-submodules/pull/2511
> Update dbaas tools

- .github/workflows/ci.yml
- service/k8sclient/internal/kubectl/kubectl_test.go
PMM-7
fix test broken in update dbaas tools PR: https://github.com/percona-platform/dbaas-controller/pull/282
> fix k8s skew test

- .github/workflows/ci.yml
- service/k8sclient/internal/kubectl/kubectl_test.go
> PMM-7 download exact version of kubectl

- service/k8sclient/k8sclient.go
> PMM-7 Fixed PSMDBCluster creation for 1.11 and 1.12 on minikube

- service/k8sclient/k8sclient.go
> PMM-7 Fixed PSMDBCluster creation for 1.11 and 1.12 on minikube (#354)

- Makefile
- service/k8sclient/k8sclient.go
- service/k8sclient/override_spec_test.go
> PMM-10679 Fixed expose for mongos on minikube

- Makefile
- service/k8sclient/k8sclient.go
- service/k8sclient/override_spec_test.go
> PMM-10679 Fixed expose configuration for PSMDB clusters

- service/operator/psmdb_operator.go
> PMM-7 Remove hardcoded value for psmdb operator

- service/olm/olm_operator.go
> PMM-11024 Added integration with dbaas-catalog

- go.mod
- go.sum
- tools/go.mod
- tools/go.sum
> PMM-7 Updated deps
